name: momapy_test
channels:
  - defaults
dependencies:
  - python=3.10
  - pygobject
  - pip
  - pip:
    - libsbgnpy
    - frozendict
    - pycairo
    - pygobject
    - numpy
    - pyparsing
    - skia-python
    - xsdata[cli, lxml, soap]
    - shapely~=2.0rc1
    - ipykernel
